name: Build & Push
on:
  push:
    branches:
      - "main"
jobs:
  build-app:
    name: App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set release version
        id: set-release-version
        run: echo "RELEASE_VERSION=lorem-ipsum" >> $GITHUB_OUTPUT
      - name: Install json parser
        run: sudo apt-get install jq
      - name: Check release version
        run: echo "Output is ${{ steps.set-release-version.outputs.RELEASE_VERSION }}"
      # - name: Build
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-infrastructure-overview
